apiVersion: apps/v1
kind: Deployment
metadata:
  name: bs-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bs-order-app
  template:
    metadata:
      labels:
        app: bs-order-app
    spec:
      containers:
        - name: bs-order-app
          image: ifraheem/bs-orders:1.1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: bookstore-env

---
apiVersion: v1
kind: Service
metadata:
  name: service-bs-order-app
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: bs-order-app
  type: LoadBalancer
