apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  selector:
    app: bookstore-app
  ports:
    - name: gateway
      port: 8080
      targetPort: 8080
    - name: auth
      port: 8000
      targetPort: 8000
    - name: catalog
      port: 5000
      targetPort: 5000
    - name: order
      port: 3000
      targetPort: 3000
    - name: rabitmq
      port: 15672
      targetPort: 15672
  type: LoadBalancer
  